package model;
// Generated 10 mai 2016 11:15:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppartenirId generated by hbm2java
 */
@Embeddable
public class AppartenirId  implements java.io.Serializable {


     private int id;
     private int idUsers;

    public AppartenirId() {
    }

    public AppartenirId(int id, int idUsers) {
       this.id = id;
       this.idUsers = idUsers;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="id_Users", nullable=false)
    public int getIdUsers() {
        return this.idUsers;
    }
    
    public void setIdUsers(int idUsers) {
        this.idUsers = idUsers;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AppartenirId) ) return false;
		 AppartenirId castOther = ( AppartenirId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getIdUsers()==castOther.getIdUsers());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getIdUsers();
         return result;
   }   


}


