package model;
// Generated 10 mai 2016 11:15:02 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Appartenir generated by hbm2java
 */
@Entity
@Table(name="Appartenir"
    ,catalog="betfun"
)
public class Appartenir  implements java.io.Serializable {


     private AppartenirId id;

    public Appartenir() {
    }

    public Appartenir(AppartenirId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="idUsers", column=@Column(name="id_Users", nullable=false) ) } )
    public AppartenirId getId() {
        return this.id;
    }
    
    public void setId(AppartenirId id) {
        this.id = id;
    }




}


