package model;
// Generated 30 mai 2016 15:21:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bet generated by hbm2java
 */
public class Bet  implements java.io.Serializable {


     private BetId id;
     private Choices choices;
     private Matchs matchs;
     private Users users;
     private Date datePari;
     private String value;

    public Bet() {
    }

    public Bet(BetId id, Choices choices, Matchs matchs, Users users, Date datePari, String value) {
       this.id = id;
       this.choices = choices;
       this.matchs = matchs;
       this.users = users;
       this.datePari = datePari;
       this.value = value;
    }
   
    public BetId getId() {
        return this.id;
    }
    
    public void setId(BetId id) {
        this.id = id;
    }
    public Choices getChoices() {
        return this.choices;
    }
    
    public void setChoices(Choices choices) {
        this.choices = choices;
    }
    public Matchs getMatchs() {
        return this.matchs;
    }
    
    public void setMatchs(Matchs matchs) {
        this.matchs = matchs;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Date getDatePari() {
        return this.datePari;
    }
    
    public void setDatePari(Date datePari) {
        this.datePari = datePari;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


