package model;
// Generated 30 mai 2016 14:17:35 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bet generated by hbm2java
 */
@Entity
@Table(name="Bet"
    ,catalog="betfunpi_BetFun"
)
public class Bet  implements java.io.Serializable {


     private BetId id;
     private Choices choices;
     private Matchs matchs;
     private Users users;
     private Date datePari;
     private String value;

    public Bet() {
    }

    public Bet(BetId id, Choices choices, Matchs matchs, Users users, Date datePari, String value) {
       this.id = id;
       this.choices = choices;
       this.matchs = matchs;
       this.users = users;
       this.datePari = datePari;
       this.value = value;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="idMatchs", column=@Column(name="id_Matchs", nullable=false) ), 
        @AttributeOverride(name="idChoices", column=@Column(name="id_Choices", nullable=false) ) } )
    public BetId getId() {
        return this.id;
    }
    
    public void setId(BetId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_Choices", nullable=false, insertable=false, updatable=false)
    public Choices getChoices() {
        return this.choices;
    }
    
    public void setChoices(Choices choices) {
        this.choices = choices;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_Matchs", nullable=false, insertable=false, updatable=false)
    public Matchs getMatchs() {
        return this.matchs;
    }
    
    public void setMatchs(Matchs matchs) {
        this.matchs = matchs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false, insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datePari", nullable=false, length=19)
    public Date getDatePari() {
        return this.datePari;
    }
    
    public void setDatePari(Date datePari) {
        this.datePari = datePari;
    }

    
    @Column(name="value", nullable=false, length=100)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


