package model;
// Generated 30 mai 2016 15:21:51 by Hibernate Tools 4.3.1



/**
 * BetId generated by hbm2java
 */
public class BetId  implements java.io.Serializable {


     private int id;
     private int idMatchs;
     private int idChoices;

    public BetId() {
    }

    public BetId(int id, int idMatchs, int idChoices) {
       this.id = id;
       this.idMatchs = idMatchs;
       this.idChoices = idChoices;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdMatchs() {
        return this.idMatchs;
    }
    
    public void setIdMatchs(int idMatchs) {
        this.idMatchs = idMatchs;
    }
    public int getIdChoices() {
        return this.idChoices;
    }
    
    public void setIdChoices(int idChoices) {
        this.idChoices = idChoices;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BetId) ) return false;
		 BetId castOther = ( BetId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getIdMatchs()==castOther.getIdMatchs())
 && (this.getIdChoices()==castOther.getIdChoices());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getIdMatchs();
         result = 37 * result + this.getIdChoices();
         return result;
   }   


}


