package model;
// Generated 10 mai 2016 11:15:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Choices generated by hbm2java
 */
@Entity
@Table(name="Choices"
    ,catalog="betfun"
)
public class Choices  implements java.io.Serializable {


     private Integer id;
     private String value;
     private int idTypesChoices;

    public Choices() {
    }

    public Choices(String value, int idTypesChoices) {
       this.value = value;
       this.idTypesChoices = idTypesChoices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="value", nullable=false, length=200)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    
    @Column(name="id_TypesChoices", nullable=false)
    public int getIdTypesChoices() {
        return this.idTypesChoices;
    }
    
    public void setIdTypesChoices(int idTypesChoices) {
        this.idTypesChoices = idTypesChoices;
    }




}


