package model;
// Generated 30 mai 2016 14:17:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Choices generated by hbm2java
 */
@Entity
@Table(name="Choices"
    ,catalog="betfunpi_BetFun"
)
public class Choices  implements java.io.Serializable {


     private Integer id;
     private TypesChoices typesChoices;
     private String value;
     private Set<Bet> bets = new HashSet<Bet>(0);

    public Choices() {
    }

	
    public Choices(TypesChoices typesChoices, String value) {
        this.typesChoices = typesChoices;
        this.value = value;
    }
    public Choices(TypesChoices typesChoices, String value, Set<Bet> bets) {
       this.typesChoices = typesChoices;
       this.value = value;
       this.bets = bets;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_TypesChoices", nullable=false)
    public TypesChoices getTypesChoices() {
        return this.typesChoices;
    }
    
    public void setTypesChoices(TypesChoices typesChoices) {
        this.typesChoices = typesChoices;
    }

    
    @Column(name="value", nullable=false, length=200)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="choices")
    public Set<Bet> getBets() {
        return this.bets;
    }
    
    public void setBets(Set<Bet> bets) {
        this.bets = bets;
    }




}


