package model;
// Generated 30 mai 2016 14:17:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="Groups"
    ,catalog="betfunpi_BetFun"
)
public class Groups  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Date dateCreation;
     private String description;
     private Set<Tournaments> tournamentses = new HashSet<Tournaments>(0);
     private Set<Matchs> matchses = new HashSet<Matchs>(0);

    public Groups() {
    }

	
    public Groups(String name, Date dateCreation) {
        this.name = name;
        this.dateCreation = dateCreation;
    }
    public Groups(String name, Date dateCreation, String description, Set<Tournaments> tournamentses, Set<Matchs> matchses) {
       this.name = name;
       this.dateCreation = dateCreation;
       this.description = description;
       this.tournamentses = tournamentses;
       this.matchses = matchses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateCreation", nullable=false, length=19)
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="groupses")
    public Set<Tournaments> getTournamentses() {
        return this.tournamentses;
    }
    
    public void setTournamentses(Set<Tournaments> tournamentses) {
        this.tournamentses = tournamentses;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="groupses")
    public Set<Matchs> getMatchses() {
        return this.matchses;
    }
    
    public void setMatchses(Set<Matchs> matchses) {
        this.matchses = matchses;
    }




}


