package model;
// Generated 3 juin 2016 13:43:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MatchComment generated by hbm2java
 */
public class MatchComment  implements java.io.Serializable {


     private Integer id;
     private Matchs matchs;
     private String comment;
     private Set<Users> userses = new HashSet<Users>(0);

    public MatchComment() {
    }

	
    public MatchComment(Matchs matchs) {
        this.matchs = matchs;
    }
    public MatchComment(Matchs matchs, String comment, Set<Users> userses) {
       this.matchs = matchs;
       this.comment = comment;
       this.userses = userses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Matchs getMatchs() {
        return this.matchs;
    }
    
    public void setMatchs(Matchs matchs) {
        this.matchs = matchs;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


