package model;
// Generated 10 mai 2016 11:15:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parier generated by hbm2java
 */
@Entity
@Table(name="Parier"
    ,catalog="betfun"
)
public class Parier  implements java.io.Serializable {


     private ParierId id;
     private Date datePari;
     private String value;

    public Parier() {
    }

    public Parier(ParierId id, Date datePari, String value) {
       this.id = id;
       this.datePari = datePari;
       this.value = value;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="idMatchs", column=@Column(name="id_Matchs", nullable=false) ), 
        @AttributeOverride(name="idChoices", column=@Column(name="id_Choices", nullable=false) ) } )
    public ParierId getId() {
        return this.id;
    }
    
    public void setId(ParierId id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datePari", nullable=false, length=19)
    public Date getDatePari() {
        return this.datePari;
    }
    
    public void setDatePari(Date datePari) {
        this.datePari = datePari;
    }

    
    @Column(name="value", nullable=false, length=100)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


