package model;
// Generated 10 mai 2016 11:15:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ParticiperId generated by hbm2java
 */
@Embeddable
public class ParticiperId  implements java.io.Serializable {


     private int id;
     private int idTournaments;

    public ParticiperId() {
    }

    public ParticiperId(int id, int idTournaments) {
       this.id = id;
       this.idTournaments = idTournaments;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="id_Tournaments", nullable=false)
    public int getIdTournaments() {
        return this.idTournaments;
    }
    
    public void setIdTournaments(int idTournaments) {
        this.idTournaments = idTournaments;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParticiperId) ) return false;
		 ParticiperId castOther = ( ParticiperId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getIdTournaments()==castOther.getIdTournaments());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getIdTournaments();
         return result;
   }   


}


