package model;
// Generated 10 mai 2016 11:15:02 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Participer generated by hbm2java
 */
@Entity
@Table(name="Participer"
    ,catalog="betfun"
)
public class Participer  implements java.io.Serializable {


     private ParticiperId id;

    public Participer() {
    }

    public Participer(ParticiperId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="idTournaments", column=@Column(name="id_Tournaments", nullable=false) ) } )
    public ParticiperId getId() {
        return this.id;
    }
    
    public void setId(ParticiperId id) {
        this.id = id;
    }




}


