package model;
// Generated 10 mai 2016 11:15:02 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PeutIntegrer generated by hbm2java
 */
@Entity
@Table(name="Peut_integrer"
    ,catalog="betfun"
)
public class PeutIntegrer  implements java.io.Serializable {


     private PeutIntegrerId id;

    public PeutIntegrer() {
    }

    public PeutIntegrer(PeutIntegrerId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="idMatchs", column=@Column(name="id_Matchs", nullable=false) ) } )
    public PeutIntegrerId getId() {
        return this.id;
    }
    
    public void setId(PeutIntegrerId id) {
        this.id = id;
    }




}


