package model;
// Generated 10 mai 2016 11:15:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PeutIntegrerId generated by hbm2java
 */
@Embeddable
public class PeutIntegrerId  implements java.io.Serializable {


     private int id;
     private int idMatchs;

    public PeutIntegrerId() {
    }

    public PeutIntegrerId(int id, int idMatchs) {
       this.id = id;
       this.idMatchs = idMatchs;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="id_Matchs", nullable=false)
    public int getIdMatchs() {
        return this.idMatchs;
    }
    
    public void setIdMatchs(int idMatchs) {
        this.idMatchs = idMatchs;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PeutIntegrerId) ) return false;
		 PeutIntegrerId castOther = ( PeutIntegrerId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getIdMatchs()==castOther.getIdMatchs());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getIdMatchs();
         return result;
   }   


}


