package model;
// Generated 30 mai 2016 14:17:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teams generated by hbm2java
 */
@Entity
@Table(name="Teams"
    ,catalog="betfunpi_BetFun"
)
public class Teams  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Date dateCreation;
     private Set<Users> userses = new HashSet<Users>(0);

    public Teams() {
    }

	
    public Teams(String name, Date dateCreation) {
        this.name = name;
        this.dateCreation = dateCreation;
    }
    public Teams(String name, String description, Date dateCreation, Set<Users> userses) {
       this.name = name;
       this.description = description;
       this.dateCreation = dateCreation;
       this.userses = userses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateCreation", nullable=false, length=19)
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="teamses")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }




}


