package model;
// Generated 30 mai 2016 14:17:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypesChoices generated by hbm2java
 */
@Entity
@Table(name="TypesChoices"
    ,catalog="betfunpi_BetFun"
)
public class TypesChoices  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set<Choices> choiceses = new HashSet<Choices>(0);

    public TypesChoices() {
    }

	
    public TypesChoices(String name) {
        this.name = name;
    }
    public TypesChoices(String name, String description, Set<Choices> choiceses) {
       this.name = name;
       this.description = description;
       this.choiceses = choiceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typesChoices")
    public Set<Choices> getChoiceses() {
        return this.choiceses;
    }
    
    public void setChoiceses(Set<Choices> choiceses) {
        this.choiceses = choiceses;
    }




}


