package model;
// Generated 3 juin 2016 13:43:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TypesChoices generated by hbm2java
 */
public class TypesChoices  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set<Choices> choiceses = new HashSet<Choices>(0);

    public TypesChoices() {
    }

	
    public TypesChoices(String name) {
        this.name = name;
    }
    public TypesChoices(String name, String description, Set<Choices> choiceses) {
       this.name = name;
       this.description = description;
       this.choiceses = choiceses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Choices> getChoiceses() {
        return this.choiceses;
    }
    
    public void setChoiceses(Set<Choices> choiceses) {
        this.choiceses = choiceses;
    }




}


