package model;
// Generated 30 mai 2016 14:17:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="Users"
    ,catalog="betfunpi_BetFun"
)
public class Users  implements java.io.Serializable {


     private Integer id;
     private String lastname;
     private String firstname;
     private boolean isAdmin;
     private boolean isMod;
     private String email;
     private Integer scores;
     private boolean isBlocked;
     private Set<Bet> bets = new HashSet<Bet>(0);
     private Set<Teams> teamses = new HashSet<Teams>(0);

    public Users() {
    }

	
    public Users(String lastname, String firstname, boolean isAdmin, boolean isMod, String email, boolean isBlocked) {
        this.lastname = lastname;
        this.firstname = firstname;
        this.isAdmin = isAdmin;
        this.isMod = isMod;
        this.email = email;
        this.isBlocked = isBlocked;
    }
    public Users(String lastname, String firstname, boolean isAdmin, boolean isMod, String email, Integer scores, boolean isBlocked, Set<Bet> bets, Set<Teams> teamses) {
       this.lastname = lastname;
       this.firstname = firstname;
       this.isAdmin = isAdmin;
       this.isMod = isMod;
       this.email = email;
       this.scores = scores;
       this.isBlocked = isBlocked;
       this.bets = bets;
       this.teamses = teamses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="lastname", nullable=false, length=100)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="firstname", nullable=false, length=100)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="isAdmin", nullable=false)
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    
    @Column(name="isMod", nullable=false)
    public boolean isIsMod() {
        return this.isMod;
    }
    
    public void setIsMod(boolean isMod) {
        this.isMod = isMod;
    }

    
    @Column(name="email", nullable=false, length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="scores")
    public Integer getScores() {
        return this.scores;
    }
    
    public void setScores(Integer scores) {
        this.scores = scores;
    }

    
    @Column(name="isBlocked", nullable=false)
    public boolean isIsBlocked() {
        return this.isBlocked;
    }
    
    public void setIsBlocked(boolean isBlocked) {
        this.isBlocked = isBlocked;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Bet> getBets() {
        return this.bets;
    }
    
    public void setBets(Set<Bet> bets) {
        this.bets = bets;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="userses")
    public Set<Teams> getTeamses() {
        return this.teamses;
    }
    
    public void setTeamses(Set<Teams> teamses) {
        this.teamses = teamses;
    }




}


