package model;
// Generated 30 mai 2016 15:21:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String lastname;
     private String firstname;
     private boolean isAdmin;
     private boolean isMod;
     private String email;
     private Integer scores;
     private boolean isBlocked;
     private String password;
     private Set<Bet> bets = new HashSet<Bet>(0);
     private Set<Teams> teamses = new HashSet<Teams>(0);

    public Users() {
    }

	
    public Users(String lastname, String firstname, boolean isAdmin, boolean isMod, String email, boolean isBlocked, String password) {
        this.lastname = lastname;
        this.firstname = firstname;
        this.isAdmin = isAdmin;
        this.isMod = isMod;
        this.email = email;
        this.isBlocked = isBlocked;
        this.password = password;
    }
    public Users(String lastname, String firstname, boolean isAdmin, boolean isMod, String email, Integer scores, boolean isBlocked, String password, Set<Bet> bets, Set<Teams> teamses) {
       this.lastname = lastname;
       this.firstname = firstname;
       this.isAdmin = isAdmin;
       this.isMod = isMod;
       this.email = email;
       this.scores = scores;
       this.isBlocked = isBlocked;
       this.password = password;
       this.bets = bets;
       this.teamses = teamses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public boolean isIsMod() {
        return this.isMod;
    }
    
    public void setIsMod(boolean isMod) {
        this.isMod = isMod;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getScores() {
        return this.scores;
    }
    
    public void setScores(Integer scores) {
        this.scores = scores;
    }
    public boolean isIsBlocked() {
        return this.isBlocked;
    }
    
    public void setIsBlocked(boolean isBlocked) {
        this.isBlocked = isBlocked;
    }
    public Set<Bet> getBets() {
        return this.bets;
    }
    
    public void setBets(Set<Bet> bets) {
        this.bets = bets;
    }
    public Set<Teams> getTeamses() {
        return this.teamses;
    }
    
    public void setTeamses(Set<Teams> teamses) {
        this.teamses = teamses;
    }

    public String getPassword() {
        return password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    




}


